name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        otp: ['19.3.6.13', '21.3.8.23', '24']
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: '3.6.1'
      - name: Compile
        run: rebar3 compile
      - name: Run EUnit Tests
        run: rebar3 eunit
